name: Update Data

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install requests
    - name: run getdata
      run: |
        python ./getdata.py
    - name: update README.md if changed
      run: |
        git diff
        git config --global user.email "oimasterfake@gmail.com"
        git config --global user.name "oimasterakioi"
        git add README.md
        git commit -m "update data"
        git push
